apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 544281168843.dkr.ecr.ap-south-1.amazonaws.com/k8s-test-repo:12
        ports:
        - containerPort: 80

