apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort   # Change to LoadBalancer in cloud environments (e.g. EKS, GKE, AKS)
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080   # Optional: define specific nodePort

